server:
  port: 9025
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  application:
    name: mall-investment-provider
  redis:
    host: localhost
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3380/mall_invest?characterEncoding=utf-8
    username: root
    password: Anbang713
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://Anbang713:pwd713@localhost:9010/eureka/